name: Setup Embedded Python
description: Downloads python embed of version specified, installs all modules in requirements.txt and gets it ready for using

inputs:
  PYTHON_VERSION:
    description: python version
    default: 3.11.4
  REQUIREMENTS_PATH:
    description: path to the requirements.txt
    default: ./setup/requirements.txt

runs:
  using: 'node20'
  main: "./dist/index.js"