name: Compile Inno Setup Script
description: |
 Compiles a .iss file and returns its tag & name
 - requires a windows action runner as inno setup is preinstalled on windows and 
 - setup script must have the version number (e.g. 1.0.0) in the output filename

inputs:
  ISS_PATH:
    description: Path to the inno setup script
    default: .\setup\setup-code.iss
outputs: 
  releaseTag:
    description: Tag of the compiled inno setup
  releaseFile:
    description: Name of compiled inno setup script

runs:
  using: 'node20'
  main: "./dist/index.js"